### ISSUE TITLE
Illegal instruction on pyhon:3.x docker images

### ISSUE THREAD

**Issue by cmnrd** [pdobsan/pynauty#13]
Many thanks for putting this python package together! This is really helpful. Unfortunately the package does not seem to work in recent docker images.

Starting a docker image like this
```
$> docker run -it --entrypoint /bin/bash "python:3.8"
```

and then installing pynauty via pip and using it in an interactive pynauty shell leads to "Illegal instruction" error:

```
root@533aa89348a5:/# pip install pynauty
Collecting pynauty
  Downloading pynauty-1.0.0-cp38-cp38-manylinux2014_x86_64.whl (318 kB)
     |████████████████████████████████| 318 kB 4.4 MB/s 
Installing collected packages: pynauty
Successfully installed pynauty-1.0.0
root@533aa89348a5:/# python
Python 3.8.8 (default, Feb 19 2021, 17:55:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> g = Graph(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Graph' is not defined
>>> from pynauty import *
>>> g = Graph(5)
>>> autgrp(g)
Illegal instruction (core dumped)
```

I am not sure what is happening here. It seems that the binary version of pynauty is used, but apparently it is incompatible with the docker image. As you can see above, gcc is at version 8.3.0 and glibc version is 2.28. Please let me know in case you need additional information

**Comment by pdobsan** [comment]
> I am not sure what is happening here. It seems that the binary version of pynauty is used, but apparently it is incompatible with the docker image.

Yes, that's right, there might be some incompatibility issue lurking here. Binary wheels of mixed python/C packages are not perfect solutions just approximations. The python packaging system cannot really help that.

You can force the recompilation by issuing

```bash
pip install --no-binary pynauty pynauty
```

Make sure that you have the requirements, C compiler, make, autoconf, installed.

Assuming that the install succeeded, you can test the result by issuing

```bash
python <path-to-installed-package>/pynauty/tests/test_minimal.py
```
If you have `pytest` installed then you can run the full test suit by issuing

```bash
pip install pytest
python -m pytest <path-to-installed-package>/pynauty
```
That takes a few seconds but then you can be sure in having a binary compatible module.

**Comment by cmnrd** [comment]
Thanks! It works when installing from source. That helps me to work around the problem.

I did some research on the topic, to find out why pip thinks the pynauty binary would be compatible to my docker image. `pip debug --verbose` indeed lists manylinux2014 as a supported platform. Based on the requirements of manylinux2014 that makes sense.

I also found that the [manylinux docker images](https://github.com/pypa/manylinux) should be used to build wheels in order to ensure full compatibility, and I think that this might be the problem here. I don't have a full overview over the GitHub Actions configuration used for building the pynauty wheels, but it seems that it builds it directly on `ubuntu-latest`, which limits compatibility. In particular [PEP 599](https://www.python.org/dev/peps/pep-0599/) defines the maximum library and compiler versions that are allowed to be used for building manylinux2014 wheels, and they are all older than the versions provided in ubuntu-latest.

**Comment by pdobsan** [comment]
@cmnrd , thanks, that what I hoped for. I am aware of the details you mentioned and have already switched to more strict wheel tagging reflecting glibc's version. Would you mind testing it, before I move the new version to pypi. But this time don't explicitly ask for no-binary let pip decide.

```bash
pip install -U -i https://test.pypi.org/simple/ pynauty
```

I expect that this automatically triggers the compilation if the glibc version incompatible with the caller's system. Still the user must have the requirements installed.

**Comment by pdobsan** [comment]
> I expect that this automatically triggers the compilation if the glibc version incompatible with the caller's system. Still the user must have the requirements installed.

In fact the requirements are only a C compiler and GNU make, one does not need autoconf.

**Comment by cmnrd** [comment]
Yes, this works!
```
$> docker run -it --entrypoint /bin/bash "python:3.8"                 
root@7c2ca2f77236:/# pip install -U -i https://test.pypi.org/simple/ pynauty
Looking in indexes: https://test.pypi.org/simple/
Collecting pynauty
  Downloading https://test-files.pythonhosted.org/packages/3a/19/a459437522eaa3d5296e184cacabd3714be453180f1e32e961e17a0999ae/pynauty-1.0.1.tar.gz (1.9 MB)
     |████████████████████████████████| 1.9 MB 3.7 MB/s 
Building wheels for collected packages: pynauty
  Building wheel for pynauty (setup.py) ... done
  Created wheel for pynauty: filename=pynauty-1.0.1-cp38-cp38-linux_x86_64.whl size=310227 sha256=4884302c02b84d6b391c474dbfde23df19591f4f41adb6ee972a352fdb440503
  Stored in directory: /root/.cache/pip/wheels/12/af/ac/7c049953ae06f20c4309f3e996674beb70bde701ef76334786
Successfully built pynauty
Installing collected packages: pynauty
Successfully installed pynauty-1.0.1
```
Also all the tests pass.

**Comment by pdobsan** [comment]
Great! I am going to upload an updated version to pypi soon.
Closing this issue as solved.
