### ISSUE TITLE
Add canonical graph labelling

### ISSUE THREAD

**Issue by sammorley-short** [pdobsan/pynauty#15]
Hi Peter! 

During my PhD I forked this package and added canonical graph labelling functionality: https://github.com/sammorley-short/pynauty. Now the package is on GitHub, perhaps we can merge this extension back into pynauty and I can scrap my fork? We may need to add some tests for the new function, but otherwise it's a pretty small change 🙂 

Thanks a bunch for creating the package in the first place. It was super useful and I was very grateful for it during my research!

**Comment by pdobsan** [comment]
Hi Sam,

I am glad that you have found pynauty useful for your research.

> I forked this package and added canonical graph labelling functionality: https://github.com/sammorley-short/pynauty. Now the package is on GitHub, perhaps we can merge this extension back into pynauty and I can scrap my fork? 

Sure, I'd  very much welcome a pull request. As you can see with the move to github and publishing on pypi I have made some changes to the source, mainly how the package is built. So I suggest the following way to go about merging the canonical labelling functionality. Fork the current version from my repo, create a branch, say `canonical-labeling`, and incorporate your changes into this branch. Make the pull request on this new branch.

For more details on how to create a pull request see the [Contributing](https://github.com/pdobsan/pynauty#contributing) section in the Readme.

**Comment by pdobsan** [comment]
Closed after merging #16.
