### ISSUE TITLE
Graph Equality Checking

### ISSUE THREAD

**Issue by JonathonMisiewicz** [pdobsan/pynauty#19]
I would like to write unit tests for my program, which requires checking that functions returning `pynauty` graph objects really do return the objects I think they do. While isomorphism checking is great, is there a reason `__eq__` on graph objects isn't implemented?

Looking at the code, this _should_ be a straightforward matter of checking equality of `number_of_vertices`, `directed` and `vertex_coloring`. `adjacency_dict` should also be the same when we regard the list of vertices as unordered sets instead. (It isn't clear to me why we insist on an ordered structure for those lists of vertices in the first place.)

**Comment by pdobsan** [comment]
On Wed, Aug 04, 2021 at 08:24:03AM -0700, Jonathon Misiewicz wrote:
> While isomorphism checking is great, is there a reason `__eq__` on
> graph objects isn't implemented?

No reason.

> regard the list of vertices as unordered sets instead. (It isn't clear
> to me why we insist on an ordered structure for those lists of
> vertices in the first place.)

There is no builtin multiset data structure.

**Comment by frankbryce** [comment]
would `pynauty.isomorphic` work for your purposes? Or are you looking for exact equality of vertex names as well?

**Comment by JonathonMisiewicz** [comment]
`pynauty.isomorphic` is enough for what I need. My code just needs to check isomorphism and compute the order of the automorphism group, so I don't need to check exact equality.

Closing the issue so that I don't have to keep this around in my head. If anybody else _does_ need equality, I have no objection to reopening.
