### ISSUE TITLE
Illegal instruction on docker images

### ISSUE THREAD

**Issue by robkh** [pdobsan/pynauty#22]
Hello! Some time ago, a colleague of mine reported a bug in docker images (#13), and unfortunately, it happened again but with more recent versions of pynauty, 1.0.1 and 1.0.2. Initially, we found the problem of illegal instruction by running on the system equipped with Intel(R) Xeon(R) CPU X5550 (which does not have AVX instructions in its ISA) and running the docker images of pythons 3.7-3.9. 

When we looked deeper, we found that the problem could be reproduced even on the processor with AVX instructions, but only for python 3.7 and 3.9. See the example on the docker image for python3.9:
```
$> docker run -it --entrypoint /bin/bash "python:3.9"
```
and the in the docker image:
```
root@0d4a3c6ba83f:/# pip install pynauty
Collecting pynauty
  Downloading pynauty-1.0.2-cp39-cp39-manylinux_2_31_x86_64.whl (320 kB)
     |████████████████████████████████| 320 kB 3.6 MB/s
Installing collected packages: pynauty
Successfully installed pynauty-1.0.2
root@0d4a3c6ba83f:/# python
Python 3.9.10 (main, Jan 18 2022, 21:15:42)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynauty import *
>>> g = Graph(5)
>>> autgrp(g)
Illegal instruction (core dumped)
```

Counter-intuitively, we could not reproduce the bug with python3.8 on the modern CPU (with AVX instructions). However, since it failed on the old processor, I looked deeper and found that the wheel for python3.8 does include the AVX instructions, e.g.:
```
    4e59: c5 fe 6f 10                   vmovdqu (%rax), %ymm2
    4e5d: c5 ed 66 c1                   vpcmpgtd  %ymm1, %ymm2, %ymm0
    4e61: c4 e2 7d 17 c0                vptest  %ymm0, %ymm0
    4e66: 74 e8                         je  0x4e50 <firstpathnode0.isra.0+0x370>
    4e68: c5 fd 6f 1d 30 b9 00 00       vmovdqa 47408(%rip), %ymm3  # 107a0 <bit+0x200>
    4e70: c4 e2 7d 8e 18                vpmaskmovd  %ymm3, %ymm0, (%rax)
```

As I learned, the wheels tagged with `manylinux_x_y_x86_64` should be able to run on any x86_64 machine with glibc version x.y. From my understanding, it means that it should even run on the old processor without AVX instructions. I found a few projects that faced a similar problem, and they resolved it by avoiding using AVX instructions (https://github.com/MacPython/pytables-wheels/issues/8).

**Comment by NebulousOinkler** [comment]
I am also facing this exact issue in Python 3.9. Is there some idea about the fix eta?

**Comment by pdobsan** [comment]
Thanks for the info. I can't really comment on how the wheels are built in a deeper level. My only suggestion would be to build locally with the newest versions of pynauty and python. I f that fails report to the python developers.
