### ISSUE TITLE
`isomorphic` doesn't handle multiple edges between vertices

### ISSUE THREAD

**Issue by frankbryce** [pdobsan/pynauty#23]
```
$ python3
>>> import pynauty
>>> a = g.Graph(2)
>>> b = g.Graph(2)
>>> a.connect_vertex(0,[1])
>>> b.connect_vertex(0,[1,1])
>>> pynauty.isomorphic(a,b)
True
```

This is unexpected. I was planning on using pynauty to model molecules, which requires multiple bonds between nodes. Is this supported by this library? If so, the `isomorphic` function is broken. If not, I think this should be caught during object construction.

Here is my local documentation of the python source

```
def isomorphic(a, b):
    '''
    Determine if two graphs are isomorphic.

    *a,b*
        Two Graph objects.

    return ->
        True if *a* and *b* are isomorphic graphs, False otherwise,
    '''
    if a.number_of_vertices != b.number_of_vertices:
        return False
    elif list(map(len, a.vertex_coloring)) != list(map(len, b.vertex_coloring)):
        return False
    else:
        return certificate(a) == certificate(b)
```

`certificate` is implemented behind the C++ veil, so I'm not sure how to inspect further to know whether more python checks are needed.

**Comment by frankbryce** [comment]
I created a pull request to avoid this confusion for future users.

One of the reasons I was confused was that the duplicate edges appeared to exist in the data structures. My pull request explicitly makes it so that this isn't the case. Users will see their duplicate edges removed when they attempt to add them. Also the doc strings are updated to mention multi-graphs are not supported.

https://github.com/pdobsan/pynauty/pull/24

**Comment by pdobsan** [comment]
Release 1.1.0 incorporated your changes. Thanks.
