### ISSUE TITLE
explicit isomorphism between graphs

### ISSUE THREAD

**Issue by punkdit** [pdobsan/pynauty#31]
Hello,

How do I find an explicit isomorphism between the vertices of two isomorphic graphs ?

**Comment by pdobsan** [comment]
On Thu, Aug 03, 2023 at 03:54:43AM -0700, Simon Burton wrote:
> How do I find an explicit isomorphism between the vertices of two isomorphic graphs ?

Let A and B be two isomorphic graphs. In pynauty that means they can be
transformed to the same canonical graph C. One can get these
isomorphisms using the canon_label() function. Let f = canon_label(A)
and g = canon_label(B) that is A --f--> C and B --g--> C. So the
function composition of g inverse and f will be an isomorphism from A to B.

**Comment by punkdit** [comment]
I've cooked up an example, it doesn't look like canon_label is respecting directed graphs, only undirected graphs..

```
A = Graph(number_of_vertices=7, directed=True,
 adjacency_dict = {
  0: [1, 5, 6],
  1: [],
  2: [3],
  3: [4, 6],
 },
 vertex_coloring = [
  set([0, 1, 2, 3]),
  set([4, 5, 6]),
 ],
)
B = Graph(number_of_vertices=7, directed=True,
 adjacency_dict = {
  0: [1],
  1: [4, 6],
  2: [3, 5, 6],
  3: [],
 },
 vertex_coloring = [
  set([0, 1, 2, 3]),
  set([4, 5, 6]),
 ],
)
f = [1, 3, 2, 0, 6, 5, 4]
g = [3, 1, 0, 2, 6, 5, 4]
```

**Comment by punkdit** [comment]
Ah, ok, i think i got this to work now:
```
>>> iso = [None]*7
>>> for i in range(7):
...   iso[f[i]] = g[i]
... 
>>> iso
[2, 3, 0, 1, 4, 5, 6]
```
and this is the isomorphism we are looking for.
