### ISSUE TITLE
Failed building wheel for pynauty

### ISSUE THREAD

**Issue by chiyuri** [pdobsan/pynauty#34]
After following the steps and all requirements installed. Installation fails at this point with feedback:

```
      copying src\pynauty\docs\html\_static\underscore.js -> build\lib.win-amd64-cpython-310\pynauty\docs\html\_static
      creating build\lib.win-amd64-cpython-310\pynauty\tests
      copying src\pynauty\tests\conftest.py -> build\lib.win-amd64-cpython-310\pynauty\tests
      copying src\pynauty\tests\test_autgrp.py -> build\lib.win-amd64-cpython-310\pynauty\tests
      copying src\pynauty\tests\test_isomorphic.py -> build\lib.win-amd64-cpython-310\pynauty\tests
      copying src\pynauty\tests\test_minimal.py -> build\lib.win-amd64-cpython-310\pynauty\tests
      running build_ext
      make nauty-objects
      error: command 'make' failed: None
      **[end of output]**

  note: This error originates from a subprocess, and is likely not a problem with pip.
  **ERROR: Failed building wheel for pynauty**
  Running setup.py clean for pynauty
Failed to build pynauty
**ERROR: Could not build wheels for pynauty, which is required to install pyproject.toml-based projects**
```

**Comment by pdobsan** [comment]
On Sat, Aug 19, 2023 at 04:27:29PM -0700, Cheyenne Powell wrote:
>       running build_ext
>       make nauty-objects
>       error: command 'make' failed: None
>       **[end of output]**


Do you have make installed?

**Comment by chiyuri** [comment]
Yes, I'm using Windows OS and I've installed, make using `winget install -e --id GnuWin32.Make` rebooted and tried again, but I'm still getting the same error.

**Comment by pdobsan** [comment]
On Sun, Aug 20, 2023 at 11:26:14AM -0700, Cheyenne Powell wrote:
> Yes, I'm using Windows OS and I've installed, make using `winget install

Ooh Windows ... I don't think nauty (and consequently pynauty) can be built
on Windows.

Your best bet is using Windows Subsystem for Linux (WSL).

**Comment by chiyuri** [comment]
Ahhh right, ok will do.
