### ISSUE TITLE
Getting nauty's source files

### ISSUE THREAD

**Issue by pdobsan** [pdobsan/pynauty#8]
I am having random problems with downloading `nauty`'s source files. They are network related, time out, broken connections etc. That could happen in the same time even when running on servers in various geographic locations. I am experiencing this with both possible sources.

I am going to contact the authors to sort this out. At the very least, I'd like to get the `....sha1sum` file provided with the tar file instead of maintaining it on our side.

**Comment by pdobsan** [comment]
I have just realized that Nauty is distributed under the Apache License, Version 2.0 so its source can be redistributed. So all our work on fetching Nauty's sources was much ado about nothing! :-(

I am going to add Nauty's sources to the package.

**Comment by goens** [comment]
Interesting, it looks like you're right about the license compatibility, although I found it curious that it would not work the other way around! I guess that's a big disadvantage of the GPL: http://www.apache.org/licenses/GPL-compatibility.html
